image: registry.gitlab.com/pages/hugo/hugo_extended:latest

cache:
  paths:
    - .cache/pip

stages:
  - test
  - build

codespell:
  stage: test
  image: python:3-slim
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - pip install codespell
  script:
    - ./scripts/spell-check.sh

test-build:
  stage: build
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"
  script:
    - hugo --minify
  artifacts:
    expire_in: 1 week
    paths:
      - public

build-and-deploy:
  stage: build
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "melroy" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  variables:
    HUGO_ENV: "production"
  script:
    - rm -rf public/
    - hugo -e production --minify
  environment:
    name: production
    url: https://blog.melroy.org
  artifacts:
    expire_in: 3 months
    paths:
      - public
