################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "18:00"
      timezone: Asia/Bangkok
    cooldown:
      default-days: 14
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 4
    assignees:
      - davidsneighbour
    target-branch: development
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "18:00"
      timezone: Asia/Bangkok
    cooldown:
      default-days: 14
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 4
    assignees:
      - davidsneighbour
    target-branch: development
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "18:00"
      timezone: Asia/Bangkok
    cooldown:
      default-days: 7
    assignees:
      - davidsneighbour
    target-branch: development
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
